#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'equalStacks' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER_ARRAY h1
#  2. INTEGER_ARRAY h2
#  3. INTEGER_ARRAY h3
#

def equalStacks(h1, h2, h3):
    # Write your code here
    sum_h1 = sum(h1)
    sum_h2 = sum(h2)
    sum_h3 = sum(h3)
    
    length_h1 = len(h1)
    length_h2 = len(h2)
    length_h3 = len(h3)
    
    idx_1 = idx_2 = idx_3 = 0
    
    while idx_1 <= length_h1 and idx_2 <= length_h2 and idx_3 <= length_h3:
        if sum_h1 == sum_h2 == sum_h3:
            return sum_h1
        min_sum = min(sum_h1, sum_h2, sum_h3)
        if sum_h1 > min_sum and idx_1 < length_h1:
            sum_h1 -= h1[idx_1]
            idx_1+=1
        if sum_h2 > min_sum and idx_2 < length_h2:
            sum_h2 -= h2[idx_2]
            idx_2+=1
        if sum_h3 > min_sum and idx_3 < length_h3:
            sum_h3 -= h3[idx_3]
            idx_3+=1
    return 0

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n1 = int(first_multiple_input[0])

    n2 = int(first_multiple_input[1])

    n3 = int(first_multiple_input[2])

    h1 = list(map(int, input().rstrip().split()))

    h2 = list(map(int, input().rstrip().split()))

    h3 = list(map(int, input().rstrip().split()))

    result = equalStacks(h1, h2, h3)

    fptr.write(str(result) + '\n')

    fptr.close()
